name: Generate Pookkalam Screenshot

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer

      - name: Generate screenshot
        run: node .github/scripts/screenshot.js

      - name: Increment version
        run: |
          VERSION_FILE=version.txt
          if [ ! -f $VERSION_FILE ]; then
            echo "1" > $VERSION_FILE
          else
            VERSION=$(cat $VERSION_FILE)
            echo $((VERSION+1)) > $VERSION_FILE
          fi
          echo "VERSION=$(cat $VERSION_FILE)" >> $GITHUB_ENV

      - name: Commit screenshot
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add my_pookkalam.png version.txt
          git commit -m "Update screenshot v${VERSION}"
          git push
